<?php

$title = 'Add new category';

$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute(
        'action', 
        $this->url(
                'nested_category', 
                array(
                    'action' => 'add',
                    'id'     => $ref_category->id
                )
        )
);
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();